[package]
name = "superhat"
version = "0.1.0"
edition = "2021"

[dependencies]
gilrs = "0.10"
tokio = { version = "1.0", features = ["full"] }
winky = { git = "https://github.com/glenmurphy/winky/" }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
crossterm = "0.27"